###
#@name login to app
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "agathe.schnoor@example.com",
  "password": "slick"
}

> {%
client.test('login success', () => {
  client.assert(response.status === 201, 'error loging in')
})
 client.global.set('auth_token', response.body.access_token)
 %}

###
#@name list profiles
GET {{host}}/profile
Authorization: Bearer {{auth_token}}

> {%
client.test('success getting profiles', () => {
  client.assert(response.status === 200, 'error getting profiels')
})
 %}

